version: '2'

services:
  mariadb:
    image: mariadb
    hostname: mariadb
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=123456
      - "MYSQL_ROOT_HOST=%"